import { createClient, SupabaseClient } from '@supabase/supabase-js';

export interface SupabaseConfig {
  url: string;
  key: string;
  bucket: string;
}

export interface SupabaseUploadResult {
  success: boolean;
  publicUrl?: string;
  fileName: string;
  fileSizeMB: number;
  bucket: string;
  error?: string;
  timestamp: string;
}

export const DEFAULT_SUPABASE_CONFIG: SupabaseConfig = {
  url: 'https://twfhqhkzabvlzkgofjyj.supabase.co',
  key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZmhxaGt6YWJ2bHprZ29manlqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4Nzk3OTU2NiwiZXhwIjoyMTAzNTU1NTY2fQ.uDMUCfyFq7rUyoZn8rFhDbGcPW4DFTWhyNlczke8Z4g',
  bucket: 'pdfs',
};

const STORAGE_KEY = 'villa7_supabase_config';

export class SupabaseStorageService {
  private static client: SupabaseClient | null = null;
  private static cachedConfig: SupabaseConfig | null = null;

  static sanitizeText(str: string): string {
    if (!str) return '';
    return str
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '') // remove acentos
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9-_]/g, '-') // remove caracteres especiais e barras
      .replace(/-+/g, '-') // remove hífens duplicados
      .replace(/^-|-$/g, ''); // remove hífens nas pontas
  }

  static getConfig(): SupabaseConfig {
    if (this.cachedConfig) return this.cachedConfig;

    const viteEnv = (import.meta as any).env || {};
    const envUrl = (viteEnv.VITE_SUPABASE_URL || '').trim();
    const envKey = (viteEnv.VITE_SUPABASE_KEY || viteEnv.VITE_SUPABASE_PUBLISHABLE_KEY || '').trim();
    const envBucket = (viteEnv.VITE_SUPABASE_BUCKET || '').trim();

    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.url === 'https://supabase.co' || parsed.url === 'http://supabase.co' || !parsed.url || parsed.url.includes('uwzfwfdonvvbdthyzcah')) {
          parsed.url = envUrl || DEFAULT_SUPABASE_CONFIG.url;
        }
        if (!parsed.key || parsed.key.includes('uwzfwfdonvvbdthyzcah') || parsed.key.includes('zlMDQVPdvxqQ8ppHrw') || parsed.key.startsWith('sb_publishable_')) {
          parsed.key = envKey && !envKey.startsWith('sb_publishable_') ? envKey : DEFAULT_SUPABASE_CONFIG.key;
        }
        if (!parsed.bucket || parsed.bucket === 'Villa7 Fotografia' || parsed.bucket.includes('@') || parsed.bucket.includes("'") || parsed.bucket.length < 2) {
          parsed.bucket = envBucket || DEFAULT_SUPABASE_CONFIG.bucket;
        }
        this.cachedConfig = {
          url: parsed.url || envUrl || DEFAULT_SUPABASE_CONFIG.url,
          key: parsed.key || envKey || DEFAULT_SUPABASE_CONFIG.key,
          bucket: parsed.bucket || envBucket || DEFAULT_SUPABASE_CONFIG.bucket,
        };
        return this.cachedConfig;
      }
    } catch {
      // fallback
    }

    this.cachedConfig = {
      url: envUrl || DEFAULT_SUPABASE_CONFIG.url,
      key: envKey || DEFAULT_SUPABASE_CONFIG.key,
      bucket: envBucket || DEFAULT_SUPABASE_CONFIG.bucket,
    };
    return this.cachedConfig;
  }

  static saveConfig(newConfig: Partial<SupabaseConfig>): SupabaseConfig {
    const current = this.getConfig();
    const updated = {
      ...current,
      ...newConfig,
      url: (newConfig.url !== undefined ? newConfig.url : current.url).trim(),
      key: (newConfig.key !== undefined ? newConfig.key : current.key).trim(),
      bucket: (newConfig.bucket !== undefined ? newConfig.bucket : current.bucket).trim() || 'pdfs',
    };
    this.cachedConfig = updated;
    this.client = null;

    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
    } catch (e) {
      console.warn('Failed to save Supabase config in localStorage', e);
    }

    return updated;
  }

  static getClient(): SupabaseClient | null {
    const config = this.getConfig();
    const cleanUrl = config.url.trim().replace(/\/+$/, '');

    if (!cleanUrl || !config.key) return null;

    if (!this.client) {
      try {
        this.client = createClient(cleanUrl, config.key.trim());
      } catch (err) {
        console.error('Error initializing Supabase client:', err);
        return null;
      }
    }

    return this.client;
  }

  /**
   * Converts a Blob to base64 string
   */
  private static async blobToBase64(blob: Blob): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64data = reader.result as string;
        const base64 = base64data.split(',')[1] || base64data;
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  }

  /**
   * Automatic function to save the PDF generated by the app to Supabase Storage
   * Uses server-side admin upload with service credentials for 100% reliable execution
   * @param arquivoPdf - The PDF Blob in memory
   * @param nomeDoAlbum - File name/label for the album (e.g. "album_joao_e_maria")
   */
  static async salvarPdfNoSupabase(
    arquivoPdf: Blob,
    nomeDoAlbum: string,
    customFilePath?: string
  ): Promise<SupabaseUploadResult> {
    const config = this.getConfig();

    // Validação preventiva de tamanho (máximo 100MB)
    const tamanhoEmMB = arquivoPdf.size / (1024 * 1024);
    if (tamanhoEmMB > 100) {
      const errMsg = `Erro: O arquivo gerado é maior do que 100MB (${tamanhoEmMB.toFixed(2)} MB).`;
      console.error(errMsg);
      return {
        success: false,
        fileName: nomeDoAlbum,
        fileSizeMB: tamanhoEmMB,
        bucket: config.bucket,
        error: errMsg,
        timestamp: new Date().toISOString(),
      };
    }

    let nomeFormatado = customFilePath;
    if (!nomeFormatado) {
      const sanitizedBase = (nomeDoAlbum || 'album_villa7')
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/\.pdf$/i, '')
        .replace(/\s+/g, '_')
        .replace(/[^a-z0-9_]/g, '');

      nomeFormatado = `${sanitizedBase || 'album_villa7'}_${Date.now()}.pdf`;
    }

    const cleanUrl = config.url.trim().replace(/\/+$/, '');

    console.log(`Iniciando upload de ${nomeFormatado} (${tamanhoEmMB.toFixed(2)} MB) para Supabase bucket "${config.bucket}"...`);
    let detailedError = '';

    // Método 1: Envio através do endpoint seguro do servidor (Admin Secret Key / RLS Bypass)
    try {
      const pdfBase64 = await this.blobToBase64(arquivoPdf);
      const res = await fetch('/api/supabase-upload', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          supabaseUrl: cleanUrl,
          supabaseKey: config.key.trim(),
          bucket: config.bucket,
          fileName: nomeFormatado,
          pdfBase64,
        }),
      });

      const contentType = res.headers.get('content-type') || '';
      if (contentType.includes('application/json')) {
        const json = await res.json();
        if (res.ok && json.success) {
          console.log('Upload para Supabase concluído com sucesso via servidor:', json.publicUrl);
          return {
            success: true,
            publicUrl: json.publicUrl,
            fileName: nomeFormatado,
            fileSizeMB: tamanhoEmMB,
            bucket: json.bucket || config.bucket,
            timestamp: new Date().toISOString(),
          };
        }
        if (json.error) {
          detailedError = json.error;
          console.warn('Servidor retornou erro:', json.error);
        }
      }
    } catch (serverErr: any) {
      detailedError = serverErr?.message || 'Falha ao conectar com o endpoint de upload.';
      console.warn('Falha no upload via servidor:', serverErr?.message || serverErr);
    }

    // Método 2: Envio direto via Supabase Storage REST API
    try {
      const cleanPath = nomeFormatado.split('/').map(encodeURIComponent).join('/');
      const restUploadUrl = `${cleanUrl}/storage/v1/object/${encodeURIComponent(config.bucket)}/${cleanPath}`;
      const restRes = await fetch(restUploadUrl, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${config.key.trim()}`,
          'apikey': config.key.trim(),
          'Content-Type': 'application/pdf',
          'x-upsert': 'true',
        },
        body: arquivoPdf,
      });

      if (restRes.ok) {
        const publicUrl = `${cleanUrl}/storage/v1/object/public/${encodeURIComponent(config.bucket)}/${cleanPath}`;
        console.log('Upload direto via Storage REST API concluído:', publicUrl);

        return {
          success: true,
          publicUrl,
          fileName: nomeFormatado,
          fileSizeMB: tamanhoEmMB,
          bucket: config.bucket,
          timestamp: new Date().toISOString(),
        };
      } else {
        const errText = await restRes.text();
        if (!detailedError) detailedError = `REST API (${restRes.status}): ${errText}`;
      }
    } catch (restErr: any) {
      console.warn('Exceção no REST API upload:', restErr?.message || restErr);
    }

    return {
      success: false,
      fileName: nomeFormatado,
      fileSizeMB: tamanhoEmMB,
      bucket: config.bucket,
      error: detailedError || `Não foi possível salvar o arquivo no Supabase Storage. Verifique se o bucket "${config.bucket}" existe no painel do Supabase.`,
      timestamp: new Date().toISOString(),
    };
  }

  /**
   * Helper para upload estruturado no formato:
   * documentos/{data}/{timestamp}_{randomId}_{nome-cliente}_{nome-arquivo}.pdf
   */
  static async uploadPdfFile(
    arquivoPdf: File | Blob,
    nomeCliente: string,
    nomeOriginalArquivo?: string,
    nomeEvento?: string,
    _telefone?: string,
    _observacao?: string
  ): Promise<SupabaseUploadResult> {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    const dateStr = `${year}-${month}-${day}`;
    const timestamp = Date.now();
    const randomId = Math.random().toString(36).substring(2, 8);

    const cleanClient = this.sanitizeText(nomeCliente || 'cliente') || 'cliente';
    const rawBase = (nomeOriginalArquivo || 'album').replace(/\.[^/.]+$/, '');
    const cleanBase = this.sanitizeText(rawBase) || 'album';
    const cleanEvent = nomeEvento ? `_${this.sanitizeText(nomeEvento)}` : '';

    const customPath = `documentos/${dateStr}/${timestamp}_${randomId}_${cleanClient}${cleanEvent}_${cleanBase}.pdf`;

    return this.salvarPdfNoSupabase(arquivoPdf, cleanBase, customPath);
  }

  /**
   * Tests connection to Supabase and checks bucket accessibility
   */
  static async testConnection(): Promise<{ success: boolean; message: string; buckets?: any[]; details?: any }> {
    const config = this.getConfig();
    const cleanUrl = config.url.trim().replace(/\/+$/, '');

    try {
      const res = await fetch('/api/supabase-test', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          supabaseUrl: cleanUrl,
          supabaseKey: config.key.trim(),
          bucket: config.bucket,
        }),
      });

      const json = await res.json();
      if (res.ok && json.success) {
        return {
          success: true,
          message: json.message || `Conexão bem sucedida com o Supabase! O bucket "${config.bucket}" está ativo.`,
          buckets: json.buckets || [],
          details: json.bucket,
        };
      }

      return {
        success: false,
        message: json.error || `Erro ao conectar com bucket "${config.bucket}". Verifique as credenciais ou se o bucket foi criado.`,
      };
    } catch (err: any) {
      return {
        success: false,
        message: `Falha na conexão com Supabase: ${err?.message || 'Verifique a rede e as configurações.'}`,
      };
    }
  }

  /**
   * Automatically creates the bucket in Supabase
   */
  static async createBucket(bucketName: string): Promise<{ success: boolean; message: string }> {
    try {
      const res = await fetch('/api/supabase-create-bucket', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ bucket: bucketName }),
      });

      const json = await res.json();
      if (res.ok && json.success) {
        return { success: true, message: json.message || `Bucket "${bucketName}" criado!` };
      }
      return { success: false, message: json.error || 'Falha ao criar bucket.' };
    } catch (e: any) {
      return { success: false, message: e.message || 'Erro de conexão.' };
    }
  }
}
